schema_version: 1

context:
  name: pyfhiaims
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfhiaims-${{ version }}.tar.gz
  sha256: 7b1ab59f49c1d4a68be5113dceda4f067fc04f8a96c92b4b62f19c6d2cb91d01

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - numpy
    - versioningit >=1.0,<2.dev0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy >=1.1.1
    - monty >=2024.10.21
    - pyyaml

tests:
  - python:
      imports:
        - pyfhiaims
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An FHI-aims official Python package
  license: MIT
  license_file: LICENSE
  homepage: https://fhi-aims-club.gitlab.io/pyfhiaims/

extra:
  recipe-maintainers:
    - jan-janssen
