schema_version: 1

context:
  name: pyfhiaims
  version: "1.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfhiaims-${{ version }}.tar.gz
  sha256: b33a0a6518185db1acd94fdc58a362861cc4db883be3bd9c8794f54b599d5aa3

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - numpy
    - versioningit >=1.0,<2.dev0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy >=1.1.1
    - monty >=2024.10.21
    - pyyaml

tests:
  - python:
      imports:
        - pyfhiaims
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: An FHI-aims official Python package
  license: MIT
  license_file: LICENSE
  homepage: https://fhi-aims-club.gitlab.io/pyfhiaims/

extra:
  recipe-maintainers:
    - jan-janssen
